title: Zambia Vote 2016!
description: "Welcome to the Malawi Election Information Centre (MEIC) - an Election Situation Room (ESR) and Citizens Journalist initiative by a coalition of Civil Society Organizations (CSOs) lead by Malawi Electoral Support Network - MESN for the 2014 Malawi Tripartite Elections."

url: zambiavote2016.org
keywords: "Malawi, Malawi Elections 2014, Malawi Tripartite Elections, 2014, MEIC, MalawiVote2014, Malawi Vote, Malawi Election Information Centre, SMAG Media UK, MESN, Malawi Electoral Support Network, Election Situation Room, OSISA, HIVOS, cashgate"

google_analytics: UA-XXXXXXX
