title: Zambia Vote 2016!
description: "Welcome to the Zambia Election Information Centre (ZEIC) - an Election Situation Room (ESR) and Citizens Journalist initiative by a coalition of Civil Society Organizations (CSOs) led by Zambia National Women's Lobby - ZNWL for the 2016 Zambia Tripartite Elections."

url: zambiavote2016.org
keywords: "Zambia, Zambia Elections 2016, Zambia Tripartite Elections, 2016, ZEIC, Triple V, ZamibiaVote2014, Zambia Vote, Zambia Election Information Centre, Code for Africa, GotToVote, GotToVote Zambia, ZNWL, Zambia National Women's Lobby, Election Situation Room, OSISA, HIVOS"

google_analytics: UA-XXXXXXX
